source ~/.config/nvim/settings.vim
source ~/.config/nvim/plugins/plugins.vim
source ~/.config/nvim/plugins/airline.vim
source ~/.config/nvim/plugins/signify.vim
source ~/.config/nvim/plugins/rainbow_parentheses.vim
source ~/.config/nvim/plugins/sneak.vim
source ~/.config/nvim/plugins/quickscope.vim
lua require'plug-colorizer'
source ~/.config/nvim/themes/nord.vim
source ~/.config/nvim/keybinds.vim
